#!/usr/bin/env bash

DESCRIPTIONS_PATH=$(dirname "$(realpath $0)")/descriptions

mkdir -p $DESCRIPTIONS_PATH
cd $DESCRIPTIONS_PATH

if [ ! -d "anymal_c_simple_description" ]; then
  git clone https://github.com/adthoms/anymal_c_simple_description
fi
